project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    - logos/julia_logo_light.svg
    - logos/github_logo_light.svg
    - images/defense.avif
    - images/defense.webp

website:
  title: "Don van den Bergh"
  navbar:
    left:
      - publications.qmd
      - software.qmd
  page-footer:
    left: Copyright © 2025 Don van den Bergh
    right:
      - text: "![](logos/github_logo_dark.svg){.quarto-dark height=1em} Github"
        href: https://github.com/vandenman
      - text: "![](logos/ORCID_iD_logo.svg){height=1em} Orcid"
        href: https://orcid.org/0000-0002-9838-7308
      - text: "![](logos/google_scholar_logo.svg){height=1em} Scholar"
        href: https://scholar.google.com/citations?user=WbbKtuQAAAAJ&hl
      - text: "![](logos/linkedIn_logo.svg){height=1em} Linkedin"
        href: https://www.linkedin.com/in/don-van-den-bergh-05500964/
  search: false # disable search for now
  favicon: logo/favicon.ico

format:
  html:
    theme:
      dark: [solar, styles.scss]
      light: [solar, styles_light.scss]
    toc: true
    include-after-head:
      text: |
        <link rel="icon" type="image/png" href="/favicon/favicon-96x96.png" sizes="96x96" />
        <link rel="icon" type="image/svg+xml" href="/favicon/favicon.svg" />
        <link rel="shortcut icon" href="/favicon/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png" />
        <link rel="manifest" href="/favicon/site.webmanifest" />
    include-after-body:
      text: |
        <script type="application/javascript" src="light-dark.js"></script>
        <script async src="https://scripts.simpleanalyticscdn.com/latest.js"></script>




